### PR TITLE
Rename Object class for PHP7.2 compatibility.

### PR DESCRIPTION
**Pull request by bensonarts**
This fixes PHP 7.2 compatibility as Object can not be a classname. The Object class has been renamed to BaseObject.

### CODE REVIEW

**Comment by nickescobedo** [comment]
This needs to be fixed. 
Drop support for PHP 5.3.

**Comment by nickescobedo** [comment]
Actually dropping 5.3 may not be necessary. TravisCI output says
`PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.`

**Comment by alainmeier** [comment]
There are some build errors that we will look into and then get this merged

**Comment by dgollahon** [comment]
Hey @bensonarts, thanks for the patch! I cherry-picked your commit and modified it for you so that the build would pass and merged it in #18.

Thanks for the helpful travis link @nickescobedo.

**Pull request closed without merging**
